auto: on
server: true
pygments: true
safe: true
authors:
  dagingaa:
    name: Dag-Inge Aas
    position: Software Developer Intern
    gravatar: d4acca0bcb24dc67644055d4e44a6b29
    web: http://www.daginge.com
    github: dagingaa
    twitter: daginge
    about: |
      Summer intern at Comoyo. Likes front-end development, new technology and cake. Currently active as Head of IT
      for [ISFiT](http://www.isfit.org).
